- name: Build a Cloud Server
  hosts: localhost # target local host
  connection: local # run actions locally
  gather_facts: False
  tasks:
    - name: Server build request
      local_action:
        module: rax
        credentials: ~/creds # rackspace cloud credentials
        name: test-server
        group: myapp
        flavor: general1-1 # 1GB server
        image: 892b9bab-a11e-4d16-b4bd-ab9494ed7b78 # Image ID for Debian Sid
        region: LON # London Region
        key_name: ansible-bastion # keypair to use
        wait: yes # wait for server to build
        count: 2
        wait_timeout: 50000
        state: present
        networks:
          - private
          - public
      register: rax

    - name: Add the instance to an ansible group called myapp
      local_action:
        module: add_host
        hostname: "{{ item.name }}"
        ansible_ssh_host: "{{ item.rax_accessipv4 }}"
        ansible_ssh_pass: "{{ item.rax_adminpass }}"
        ansible_ssh_user: root
        groupname: myapp
      with_items: rax.success
      when: rax.action == 'create'

- name: Wait for port 22 to be ready
  hosts: myapp
  gather_facts: False
  tasks:
    - local_action: wait_for port=22 host="{{ ansible_ssh_host }}" search_regex=OpenSSH delay=10

- name: Install Packages
  hosts: myapp
  user: "{{ ansible_ssh_user }}"
  gather_facts: False
  tasks:
  - name: Update apt cache
    apt: update_cache=yes

  - name: Install Useful Packages
    action: apt state=installed pkg={{ item }}
    with_items:
    - vim
    - git
    - tmux

- name: Install and Configure Nginx
  hosts: myapp
  user: "{{ ansible_ssh_user }}"
  gather_facts: True
  tasks:

  - name: Install Nginx Package
    action: apt state=installed pkg={{ item }}
    with_items:
    - nginx

  - name: Add a simple index file
    action: lineinfile dest=/var/www/html/index.html create=yes state=present line="This is {{ ansible_hostname }}"

- name: Build a Cloud Load Balancer and add servers to it
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Load Balancer create request
      local_action:
        module: rax_clb
        credentials: ~/creds
        name: my-web-site
        port: 80
        protocol: HTTP
        algorithm: ROUND_ROBIN
        type: PUBLIC
        timeout: 30
        region: LON
        wait: yes
        state: present
        meta:
          app: my-cool-app
      register: clb

    - name: Add servers to Load Balancer
      with_items: groups['myapp']
      local_action:
        module: rax_clb_nodes
        credentials: ~/creds
        load_balancer_id: "{{ clb.balancer.id }}"
        address: "{{ hostvars[item]['ansible_ssh_host'] }}"
        port: 80
        condition: enabled
        type: primary
        wait: yes
        region: LON
